version: 3

tasks:
  build:
    deps:
      - task: build_module
        vars: { NAME: "sprinkle" }
      - task: build_module
        vars: { NAME: "domainify" }
      - task: build_module
        vars: { NAME: "coolify" }
      - task: build_module
        vars: { NAME: "synonyms" }
      - task: build_module
        vars: { NAME: "available" }
    cmds:
      - echo "build done"
    silent: true

  build_module:
    cmds:
      - go build -o bin/{{.NAME}} {{.NAME}}/main.go
    sources:
      - ./{{.NAME}}/main.go
    generates:
      - ./bin/{{.NAME}}
    method: timestamp

  build_deps:
    dir: thesaurus
    cmds:
      - go build
